# Introduction to NumPy
Prepared by Jen Nunnelley with influence from Nickolas Freeman, Ph.D. and Irem Sengul orgut, Ph.D.

This notebook provides an introduction to the `numpy` package. The content borrows heavily from the book *Data Science Handbook*, which was written by Jake VanderPlas and is available at https://jakevdp.github.io/PythonDataScienceHandbook/ (accessed 12/17/2019).

The following table of contents lists the topics discussed in this notebook. Clicking on any topic will advance the notebook to the associated area.


# Table of Contents
<a id="Table_of_Contents"> </a>

1. [NumPy](#numpy)<br>
    1.1 [Importing NumPy](#Importing_NumPy)<br>
    1.2 [NumPy Arrays](#NumPy_Arrays)<br>
    1.3 [Basic Computations using NumPy Arrays](#Array_Computation)<br>
    1.4 [Aggregations](#Array_Aggregations)<br>   
    
#### Disclaimer

This notebook is by no means a comprehensive resource for the `numpy` package. Also, it is important to realize that the Python language and the available packages will continue to evolve. That being said, the objects, functions, and methods described in this notebook may one day change. If changes occur, areas of this notebook that use deprecated features may cease to work and will need to be revised or omitted.

## NumPy
<a id="numpy"> </a>

This section of the notebook will introduce the `numpy` package and demonstrate several features of the `numpy` multi-dimensional array. 

From https://en.wikipedia.org/wiki/NumPy (accessed on 1/6/2018):

>NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays. The ancestor of NumPy, Numeric, was originally created by Jim Hugunin with contributions from several other developers. In 2005, Travis Oliphant created NumPy by incorporating features of the competing Numarray into Numeric, with extensive modifications. NumPy is open-source software and has many contributors.

[Back to Table of Contents](#Table_of_Contents)<br>

## Importing NumPy
<a id="Importing_NumPy"> </a>

Users can import available packages and modules using Python's `import` statement. Two forms of import expressions are commonly used.
1. The first common import expression takes the form **import mypackage as mp**. This statement imports a package named *mypackage*, and assigns it to the alias *mp*. Suppose that *mypackage* contains the definition for a function named *myfunction*. If this were true, we would call *myfunction* using the syntax `mp.myfunction(*args)`, where `*args` is a placeholder for any function arguments.<br>

2. The second common import expression takes the form **from mypackage import mysubmodule**. This statement imports a specific submodule from a package named *mypackage*. Since there is no alias, this type of import will bring in the functions specified in the submodule as they are writtin. For example, if the submodule *mysubmodule* includes a function called *myfunction*, we would call *myfunction* using the syntax `myfunction(*args)`, where `*args` is a placeholder for any function arguments.

<div class="alert alert-block alert-danger">
    <b>Name conflicts with <i>from - import</i> approach:</b> When using the <i>from - import</i> approach sepcified in bullet 2, it is important to make sure that method names in package or module you are importing do not conflict with names defined in the importing code. For example, if we import a submodule named *mysubmodule* that includes a function called *myfunction*, but we also have a function named *myfunction* in the importing code, there will be a naming conflict.
</div>

The following code block uses the *import - as* approach to import NumPy. The alias *np* is a standard convention.

[Back to Table of Contents](#Table_of_Contents)<br>

<b> Using the first way to import packages, import NumPy. <b>

In [2]:
import numpy as np

#### Motivation for NumPy

Before we look at specific details of the NumPy package, it is important to understand its motivation. NumPy was developed to support scientific computations via the efficient implementation of a multi-dimensional array. In addition to an efficient array implementation, NumPy also includes functions for performing operations on NumPy arrays that are optimized for computational efficeincy. The following code block illustrate the substantial increas in efficiency that NumPy provides in comparison to a standard python list. Specifically, the example considers the task of adding two vectors of a specified size using both standard Python lists and NumPy arrays. The time of the addition, and the size of the resulting objects are reported for comparison purposes.


<div class="alert alert-block alert-info">
    <b>The <i>del()</i> function:</b> The <i>del()</i> function is a python method that deletes a created object from memory. For example, <i>del(my_var)</i> deletes a Python variable named <i>my_var</i>, freeing any computer memory that was being used to store the variable. The <i>del(my_var)</i> can take multiple arguments. For example, <i>del(my_var1, my_var2)</i> deletes the Python variables named <i>my_var1</i> and <i>my_var2</i>. If you pass an argument to <i>del(my_var)</i> that does not correspond to an existing Python object, an error will be raised.
</div>

[Back to Table of Contents](#Table_of_Contents)<br>

In [2]:
import time
print(time.time())

1573498118.8610814


In [3]:
import time
import sys

SIZE = 100000

# Using Python List
list1 = range(SIZE)
list2 = range(SIZE)

start = time.time()
result = [(x+y) for x,y in zip(list1,list2)]
print("Using Python lists, the addition took",(time.time() - start)*1000,"milliseconds.")
print("The size of the result object based on Python lists is",sys.getsizeof(result),"bytes.\n")

del(list1, list2, result)

#Using NumPy List
nparray1 = np.arange(SIZE)
nparray2 = np.arange(SIZE)
start = time.time()
result = nparray1 + nparray2
print("Using NumPy arrays, the addition took",(time.time() - start)*1000,"milliseconds.")
print("The size of the result object based on NumPy arrays is",sys.getsizeof(result),"bytes.\n")

del(nparray1, nparray2, result)

Using Python lists, the addition took 10.998010635375977 milliseconds.
The size of the result object based on Python lists is 824464 bytes.

Using NumPy arrays, the addition took 0.0 milliseconds.
The size of the result object based on NumPy arrays is 400096 bytes.



In addition to demonstrating the substantial performance gains offered by NumPy, the previous code block also illsutrates some of the subtle differences of working with Python lists and NumPy arrays, and a method for checking the computation time that is required to execute a portion of code. Specifically:

- The `time.time()` function, from the `time` module, returns the current system time. Saving the value of the current time in a variable `start` and then computing the difference `time.time() - start` returns the seconds elapsing between the two calls to `time.time()` in seconds. Multiplying by 1000 converts the elapsed time to milliseconds.


- When working with Python lists, the `range()` function returns a sequence of integers starting at zero and ending at the argument passed to `range()`. In our example, we pass a variable `SIZE` to the `range()` function. Thus, the sequence stored in the list is 0, 1, ..., `SIZE`-2, `SIZE`-1.


- When working with NumPy arrays, the `np.range()` function returns a sequence of integers starting at zero and ending at the argument passed to `np.arange()`. In our example, we pass a variable `SIZE` to the `np.arange()` function. Thus, the sequence stored in the NumPy array is 0, 1, ..., `SIZE`-2, `SIZE`-1.


- The `sys.getsizeof()` function, from the `sys` library, returns the size of an object in bytes.


- When working with Python lists, the `zip()` function essentially combines two or more list objects and allows element-wise operations to be performed.


- When working with NumPy arrays, there is no need to *zip* arrays. Instead, element-wise operations are performed using standard mathematical operators.

[Back to Table of Contents](#Table_of_Contents)<br>

#### Searching for Relevant NumPy Methods

A final interesting thing to note is that the NumPy package includes a method to search for other methods that may be used to accomplish a desired task. This is extremely helpful given the large size of the package. As an example, suppose that we are interested in methods that work with the *standard deviation* for a set of numbers. The following code block shows how NumPy's `lookfor()` method allows us to search for such methods.

[Back to Table of Contents](#Table_of_Contents)<br>

In [4]:
np.lookfor('standard deviation')

TypeError: 'NoneType' object is not iterable

### NumPy Arrays
<a id="NumPy_Arrays"> </a>

The key data structure used by NumPy is the multi-dimensional array or `ndarray`. The following code blocks demonstrate. several methods for creating numpy arrays.

<div class="alert alert-block alert-info">
    <b>NumPy's <i>random</i> module:</b> The final two examples utilize random number generators from NumPy's <i>random</i> module. The methods available in this module can be accessed via the prefix <i>np.random.</i> (this assumes NumPy was imported as np).
</div>

[Back to Table of Contents](#Table_of_Contents)<br>

<b>Create a one dimensional (1-d) array with a list<b>

In [ ]:
np.array([1,2,3,4])

<b>Create a two-dimensional (2-d) array with a list.  Use a variable called my_list to store thbis list in. <b>

In [ ]:
my_list = [[1,2,3,4],
           [5,6,7,8]]

np.array(my_list)

<b>Create a two-dimensional array of size 4 x 5 (4 rows and 5 columns) that is filled with all zeros. <b>

In [ ]:
np.zeros((4,5))

<b> Create a two-dimensional array that is 5 x 3 matrix filled with values randomly drawn from a continuous uniform distribution that ranges from 0 to 100.<b>

In [ ]:
np.random.uniform(low = 0.0, high = 100.0, size = (5, 3))

<b> Create a two-dimensional array that is 5 x 3 matrix filled with values randomly drawn from a continuous uniform distribution that ranges from 0 to 10 in integer form.<b>

In [ ]:
np.random.randint(low = 1, high = 10, size = (5, 3))

<b>Create a two-dimensional 3 x 3 matrix filled with values randomly drawn from a normal distribution with a mean of 10.0 and standard deviation of 2.0<b>

In [ ]:
np.random.normal(loc=10,scale=2, size=(3,3))

The following code blocks demonstrate several attributes of NumPy arrays that we can use to gain information regarding their structure.

<b>Create a two-dimensional 3 x 5 matrix filled with values randomly drawn from a normal distribution with a mean of 10.0 and standard deviation of 2.0 and store the array in a variable named my_array.  We will use this variable to sho the different attributes NumPy has available.<b>

In [3]:
my_array = np.random.normal(loc = 10.0, scale = 2.0, size = (3, 5))
print(my_array)

[[ 9.97613757 12.14104881  8.5126193   8.35565514 11.48978646]
 [12.66150621  7.7233989  11.41664179  9.58401604 10.42992577]
 [ 9.78671548 12.36713087 14.189676    8.98728187  9.98926976]]


<b>Use the shape attribute to get the shape of the array<b>

In [4]:
print("The shape of my_array is", my_array.shape,".")

The shape of my_array is (3, 5) .


<b>Use the size attribute to get the size of the array.  (aka, how many entries are there)<b>

In [ ]:
print("my_arry has",my_array.size,"entries.")

<b>Use the dtype attribute to determine the data type for my_array<b>

In [ ]:
print("The data type for entries of my_array is", my_array.dtype,".")

###  Basic Computations with NumPy Arrays
<a id="Array_Computation"> </a>

NumPy is able to achieve fast computation times through the use of *vectorized* operations. Essentially, instead of performing operations on NumPy array elements one at a time, NumPy operations can be performed on entire arrays or slices of arrays. The following code block shows some examples.

[Back to Table of Contents](#Table_of_Contents)<br>

<b>Create two two-dimensional 3 x 5 arrays, the first with values randomly drawn from a uniform distribution with low and high values of 0.0 and 1.0, respectively, and the second with values drawn from discrete uniform distribution ranging from 1 to 10.<b>


In [5]:
array1 = np.random.uniform(low = 0.0, high = 1.0, size = (3, 5))
array2 = np.random.randint(low = 1, high = 10, size = (3, 5))
print(array1)
print(array2)

[[0.24786369 0.96292589 0.83975735 0.58643338 0.71428381]
 [0.33913017 0.52540508 0.57186841 0.84967951 0.21001762]
 [0.42285388 0.14567608 0.951432   0.5714269  0.15652895]]
[[5 5 5 9 9]
 [1 8 2 5 1]
 [3 8 2 7 9]]


<b>Add the arrays together<b>

In [ ]:
array1+array2

<b>Subtract array1 from array2<b>

In [ ]:
array2-array1

<b>Add 1 to all elements of array1<b>

In [ ]:
array1+1

<b>Compute 20*(array1^2)-array2<b>

In [ ]:
20*(array1**2)-array2

<b>Compute the absolute value for 20*(array1^2)-array2<b>

In [ ]:
abs(20*(array1**2)-array2)

<b> Delete the variables array1 and array2 from the computer. <b>

In [ ]:
del(array1, array2)

### Aggregations
<a id="Array_Aggregations"> </a>

In addition to performing computations on each element of an array, NumPy also allows users to perform aggregations accross all elements and to perform computations along a particular array *axis*. Before continuing, it is important to understand exactly what is meant by an *array axis*.

In NumPy, *axes* are defined for arrays with more than one dimension. For example, a 2-dimensional array has two axes: the first running vertically downwards across rows (axis 0), and the second running horizontally across columns (axis 1). Another way to think about this is if I have an $mxn$ array, where $m$ is the number of rows and $n$ the number of columns, the first axis, axis 0, runs across the $m$ rows and the second axis, axis 1, runs across the $n$ columns. 

Using this concept of array axes, we can do computations across rows and columns of arrays. The following code blocks provide examples.

NumPy provides many other aggregation functions, but we won't discuss them in detail here.

The following table provides a list of useful aggregation functions available in NumPy:

|Function Name      | Description                                   |
|-------------------|-----------------------------------------------|
| ``np.sum``        | Compute sum of elements                       |
| ``np.prod``       | Compute product of elements                   |
| ``np.mean``       | Compute mean of elements                      |
| ``np.std``        | Compute standard deviation                    |
| ``np.var``        | Compute variance                              |
| ``np.min``        | Find minimum value                            |
| ``np.max``        | Find maximum value                            |
| ``np.argmin``     | Find index of minimum value                   |
| ``np.argmax``     | Find index of maximum value                   |
| ``np.median``     | Compute median of elements                    |
| ``np.percentile`` | Compute rank-based statistics of elements     |
| ``np.any``        | Evaluate whether any elements are true        |
| ``np.all``        | Evaluate whether all elements are true        |

[Back to Table of Contents](#Table_of_Contents)<br>

<b>Create a two-dimensional 3 x 5 array with values drawn from discrete uniform distribution ranging from 1 to 10 in whole numbers.<b>

In [ ]:
my_array1 = np.random.randint(low = 1, high = 10, size = (3, 5))
print(my_array1)

<b>Sum all values in my_array1<B>

In [ ]:
np.sum(my_array1)

<b>Sum the values in each row.<Br>
Note that we need to sum the values across each column, or axis 1.<b>

In [ ]:
np.sum(my_array1, axis = 1)

<b>Sum the values in each column.<Br>
Note that we need to sum the values across each row, or axis 1.<b>

In [ ]:
np.sum(my_array1, axis = 0)

<b>Find the maximum value in each row<B>

In [ ]:
np.max(my_array1, axis = 1)